## Preprocessing

In [127]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf
import keras_tuner as kt
from sklearn.metrics import classification_report


#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [128]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
#application_df = application_df.drop(columns =["EIN","NAME"])

application_df = application_df.drop(columns =["EIN", "NAME"])

application_df

# number_input_features = len(X_train[0])
# hidden_nodes_layer1 =  100
# hidden_nodes_layer2 = 30
# hidden_nodes_layer3 = 10

# nn = tf.keras.models.Sequential()

# nn.add(
#     tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation="relu")
# )

# nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation="sigmoid"))

# nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer3, activation="sigmoid"))

# # Output layer
# nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# name_counts = application_df['NAME'].value_counts()
# name_counts[name_counts>5]

# names_to_replace = list(name_counts[name_counts <= 5].index)

# for app in names_to_replace:
#     application_df['NAME'] = application_df['NAME'].replace(app,"Other")

# application_df['NAME'].value_counts()

# nn.summary()

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1
...,...,...,...,...,...,...,...,...,...,...
34294,T4,Independent,C1000,ProductDev,Association,1,0,N,5000,0
34295,T4,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
34296,T3,CompanySponsored,C2000,Preservation,Association,1,0,N,5000,0
34297,T5,Independent,C3000,ProductDev,Association,1,0,N,5000,1
34298,T3,Independent,C1000,Preservation,Co-operative,1,1M-5M,N,36500179,0

In [129]:
# Determine the number of unique values in each column.
application_df.nunique()

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [130]:
# # Look at APPLICATION_TYPE value counts to identify and replace with "Other"
print(application_df["APPLICATION_TYPE"].value_counts())

# application_df = application_df.replace(["T25","T14","T29","T15","T17", "T2", "T13", "T12"], "Other")

# application_df

# res  = application_df["APPLICATION_TYPE"].value_counts()

# res

# #change up T replaced values

APPLICATION_TYPE
T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: count, dtype: int64

In [131]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
#  YOUR CODE GOES HERE

# Replace in dataframe
# for app in application_types_to_replace:
#     application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# # Check to make sure replacement was successful
# application_df['APPLICATION_TYPE'].value_counts()

In [132]:
# Look at CLASSIFICATION value counts to identify and replace with "Other"
app_class = application_df["CLASSIFICATION"].value_counts()

app_class

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: count, Length: 71, dtype: int64

In [133]:
# You may find it helpful to look at CLASSIFICATION value counts >1
app_class_2 = app_class[app_class >= 1]

app_class_2 = app_class_2.reset_index()

In [134]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`

# app_class_2 = app_class[app_class <= 1]

# app_class_2 = app_class_2.reset_index()

# classifications_to_replace = list(app_class_2["CLASSIFICATION"])

# # Replace in dataframe
# for cls in classifications_to_replace:
#     application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

# # Check to make sure replacement was successful
# application_df['CLASSIFICATION'].value_counts()

# #classifications_to_replace

In [135]:
# Convert categorical data to numeric with `pd.get_dummies`
dummy_pd = pd.get_dummies(application_df, drop_first = False).astype(int)

dummy_pd

#try one hot encoder 

# print(dummy_pd.columns[0:81])

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_T10,APPLICATION_TYPE_T12,APPLICATION_TYPE_T13,APPLICATION_TYPE_T14,APPLICATION_TYPE_T15,APPLICATION_TYPE_T17,APPLICATION_TYPE_T19,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,1,108590,1,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,1,0
2,1,5000,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
3,1,6692,1,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,1,0
4,1,142590,1,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34294,1,5000,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
34295,1,5000,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
34296,1,5000,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
34297,1,5000,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
34298,1,36500179,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,1,0

In [136]:
print(dummy_pd.columns[0:81])

Index(['STATUS', 'ASK_AMT', 'IS_SUCCESSFUL', 'APPLICATION_TYPE_T10',
       'APPLICATION_TYPE_T12', 'APPLICATION_TYPE_T13', 'APPLICATION_TYPE_T14',
       'APPLICATION_TYPE_T15', 'APPLICATION_TYPE_T17', 'APPLICATION_TYPE_T19',
       'APPLICATION_TYPE_T2', 'APPLICATION_TYPE_T25', 'APPLICATION_TYPE_T29',
       'APPLICATION_TYPE_T3', 'APPLICATION_TYPE_T4', 'APPLICATION_TYPE_T5',
       'APPLICATION_TYPE_T6', 'APPLICATION_TYPE_T7', 'APPLICATION_TYPE_T8',
       'APPLICATION_TYPE_T9', 'AFFILIATION_CompanySponsored',
       'AFFILIATION_Family/Parent', 'AFFILIATION_Independent',
       'AFFILIATION_National', 'AFFILIATION_Other', 'AFFILIATION_Regional',
       'CLASSIFICATION_C0', 'CLASSIFICATION_C1000', 'CLASSIFICATION_C1200',
       'CLASSIFICATION_C1230', 'CLASSIFICATION_C1234', 'CLASSIFICATION_C1235',
       'CLASSIFICATION_C1236', 'CLASSIFICATION_C1237', 'CLASSIFICATION_C1238',
       'CLASSIFICATION_C1240', 'CLASSIFICATION_C1245', 'CLASSIFICATION_C1246',
       'CLASSIFICATION_C1248', 'CLASSIFICATION_C1250', 'CLASSIFICATION_C1256',
       'CLASSIFICATION_C1257', 'CLASSIFICATION_C1260', 'CLASSIFICATION_C1267',
       'CLASSIFICATION_C1270', 'CLASSIFICATION_C1278', 'CLASSIFICATION_C1280',
       'CLASSIFICATION_C1283', 'CLASSIFICATION_C1300', 'CLASSIFICATION_C1370',
       'CLASSIFICATION_C1400', 'CLASSIFICATION_C1500', 'CLASSIFICATION_C1570',
       'CLASSIFICATION_C1580', 'CLASSIFICATION_C1600', 'CLASSIFICATION_C1700',
       'CLASSIFICATION_C1720', 'CLASSIFICATION_C1728', 'CLASSIFICATION_C1732',
       'CLASSIFICATION_C1800', 'CLASSIFICATION_C1820', 'CLASSIFICATION_C1900',
       'CLASSIFICATION_C2000', 'CLASSIFICATION_C2100', 'CLASSIFICATION_C2150',
       'CLASSIFICATION_C2170', 'CLASSIFICATION_C2190', 'CLASSIFICATION_C2300',
       'CLASSIFICATION_C2380', 'CLASSIFICATION_C2400', 'CLASSIFICATION_C2500',
       'CLASSIFICATION_C2561', 'CLASSIFICATION_C2570', 'CLASSIFICATION_C2600',
       'CLASSIFICATION_C2700', 'CLASSIFICATION_C2710', 'CLASSIFICATION_C2800',
       'CLASSIFICATION_C3000', 'CLASSIFICATION_C3200', 'CLASSIFICATION_C3700',
       'CLASSIFICATION_C4000'],
      dtype='object')

In [137]:
# # Split our preprocessed data into our features and target arrays
# X = dummy_pd.drop(columns = ['IS_SUCCESSFUL'])
# y = dummy_pd["IS_SUCCESSFUL"]

# # # Split the preprocessed data into a training and testing dataset
# X_train, X_test, y_train, y_test = train_test_split(X, y, random_state = 78)

# len(X.columns)


print(dummy_pd["INCOME_AMT_50M+"].value_counts())

print(dummy_pd['AFFILIATION_Other'].value_counts())

INCOME_AMT_50M+
0    34160
1      139
Name: count, dtype: int64
AFFILIATION_Other
0    34295
1        4
Name: count, dtype: int64

In [138]:
# Split our preprocessed data into our features and target arrays

#  
X = dummy_pd.drop(columns = ["IS_SUCCESSFUL", "STATUS", "SPECIAL_CONSIDERATIONS_N", "SPECIAL_CONSIDERATIONS_Y", "AFFILIATION_Regional", "AFFILIATION_Other"])
y = dummy_pd["IS_SUCCESSFUL"]

# # Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state = 42)

# len(X.columns)

# print(X.columns)

# len(X_train)

In [139]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

scale_pd = pd.DataFrame(X_train_scaled)

scale_pd.iloc[:, 10:60]

,10,11,12,13,14,15,16,17,18,19,...,50,51,52,53,54,55,56,57,58,59
0,-0.008818,0.519562,-0.219362,-0.187983,-0.192155,-0.14781,-0.146985,-0.067304,1.086533,-0.04413,...,-0.012471,-0.091591,-0.013943,-0.006235,-0.006235,-0.01972,-0.006235,0.0,-0.465599,-0.244049
1,-0.008818,0.519562,-0.219362,-0.187983,-0.192155,-0.14781,-0.146985,-0.067304,-0.920358,-0.04413,...,-0.012471,-0.091591,-0.013943,-0.006235,-0.006235,-0.01972,-0.006235,0.0,-0.465599,-0.244049
2,-0.008818,0.519562,-0.219362,-0.187983,-0.192155,-0.14781,-0.146985,-0.067304,1.086533,-0.04413,...,-0.012471,-0.091591,-0.013943,-0.006235,-0.006235,-0.01972,-0.006235,0.0,-0.465599,-0.244049
3,-0.008818,0.519562,-0.219362,-0.187983,-0.192155,-0.14781,-0.146985,-0.067304,1.086533,-0.04413,...,-0.012471,-0.091591,-0.013943,-0.006235,-0.006235,-0.01972,-0.006235,0.0,-0.465599,4.097532
4,-0.008818,-1.924698,-0.219362,-0.187983,-0.192155,6.76542,-0.146985,-0.067304,1.086533,-0.04413,...,-0.012471,-0.091591,-0.013943,-0.006235,-0.006235,-0.01972,-0.006235,0.0,-0.465599,-0.244049
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25719,-0.008818,0.519562,-0.219362,-0.187983,-0.192155,-0.14781,-0.146985,-0.067304,-0.920358,-0.04413,...,-0.012471,-0.091591,-0.013943,-0.006235,-0.006235,-0.01972,-0.006235,0.0,-0.465599,-0.244049
25720,-0.008818,0.519562,-0.219362,-0.187983,-0.192155,-0.14781,-0.146985,-0.067304,-0.920358,-0.04413,...,-0.012471,-0.091591,-0.013943,-0.006235,-0.006235,-0.01972,-0.006235,0.0,-0.465599,-0.244049
25721,-0.008818,0.519562,-0.219362,-0.187983,-0.192155,-0.14781,-0.146985,-0.067304,-0.920358,-0.04413,...,-0.012471,-0.091591,-0.013943,-0.006235,-0.006235,-0.01972,-0.006235,0.0,-0.465599,-0.244049
25722,-0.008818,0.519562,-0.219362,-0.187983,-0.192155,-0.14781,-0.146985,-0.067304,1.086533,-0.04413,...,-0.012471,-0.091591,-0.013943,-0.006235,-0.006235,-0.01972,-0.006235,0.0,-0.465599,-0.244049
25723,-0.008818,0.519562,-0.219362,-0.187983,-0.192155,-0.14781,-0.146985,-0.067304,-0.920358,-0.04413,...,-0.012471,-0.091591,-0.013943,-0.006235,-0.006235,-0.01972,-0.006235,0.0,-0.465599,-0.244049

In [140]:
pd.DataFrame(X_train).iloc[:,4].value_counts()

#imbalanced data sets 

#accuracy vs precsion recall

#three things to consider: Number of layer, nodes per layer, activation function

APPLICATION_TYPE_T14
0    25722
1        2
Name: count, dtype: int64

In [141]:
# h = kt.HyperParameters()

# activation = h.Choice('activation', ['relu','tanh','sigmoid'])

# len(X_train[0])

## Compile, Train and Evaluate the Model

In [142]:
# def create_model(h):
#     nn = tf.keras.models.Sequential()

#     x_features = len(X_train.iloc[0])
    
#     activation = h.Choice('activation', ['relu','tanh'])
    
#     nn.add(tf.keras.layers.Dense(units=h.Int('first_units',
#         min_value=1,
#         max_value=50,
#         step=2), activation=activation, input_dim=x_features))

#     for i in range(h.Int('num_layers', 1, 15)):
#         nn.add(tf.keras.layers.Dense(units=h.Int('units_' + str(i),
#             min_value=1,
#             max_value=50,
#             step=2),
#             activation=activation))

#     # Output layer
#     nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

#     nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

#     return nn

In [143]:
def create_model(h):
    nn = tf.keras.models.Sequential()

    x_features = len(X_train.iloc[0])
    
    activation = h.Choice('activation', ['relu','tanh', "sigmoid"])
    
    nn.add(tf.keras.layers.Dense(units=h.Int('first_units',
        min_value=1,
        max_value=50,
        step=2), activation=activation, input_dim=x_features))

    for i in range(h.Int('num_layers', 1, 12)):
        nn.add(tf.keras.layers.Dense(units=h.Int('units_' + str(i),
            min_value=1,
            max_value=81,
            step=2),
            activation=activation))

    # Output layer
    nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

    nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

    return nn

In [144]:
tuner = kt.Hyperband(
    create_model,
    objective="val_accuracy",
    max_epochs=30,
    hyperband_iterations=2)

Reloading Tuner from .\untitled_project\tuner0.json

In [151]:
tuner.search(X_train_scaled,y_train,epochs=50,validation_data=(X_test_scaled,y_test))

In [146]:
# # Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
# #  YOUR CODE GOES HERE

h = kt.HyperParameters()

activation = h.Choice('activation', ['relu','tanh','sigmoid'])

nn2 = tf.keras.models.Sequential()

x_features = len(X_train.iloc[0])
# First hidden layer
nn2.add(
    tf.keras.layers.Dense(units=80, input_dim=x_features, activation=activation)
)

nn2.add(
    tf.keras.layers.Dense(units=65, activation=activation)
)

# nn2.add(
#     tf.keras.layers.Dense(units=50, activation=activation)
# )

nn2.add(
    tf.keras.layers.Dense(units=33, activation=activation)
)
# Second hidden layer

nn2.add(
    tf.keras.layers.Dense(units=20, activation=activation)
)


# nn2.add(
#     tf.keras.layers.Dense(units=12, activation=activation)
# )

nn2.add(
    tf.keras.layers.Dense(units=6, activation=activation)
)

# Output layer
nn2.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn2.summary()

c:\Users\librarypc\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_13 (Dense)                │ (None, 80)             │         8,960 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_14 (Dense)                │ (None, 65)             │         5,265 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_15 (Dense)                │ (None, 33)             │         2,178 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_16 (Dense)                │ (None, 20)             │           680 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_17 (Dense)                │ (None, 6)              │           126 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_18 (Dense)                │ (None, 1)              │             7 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 17,216 (67.25 KB)

 Trainable params: 17,216 (67.25 KB)

 Non-trainable params: 0 (0.00 B)

In [147]:
# h = kt.HyperParameters()

# activation = h.Choice('activation', ['relu','tanh','sigmoid'])

# nn2 = tf.keras.models.Sequential()

# x_features = len(X_train.iloc[0])
# # First hidden layer
# nn2.add(
#     tf.keras.layers.Dense(units=80, input_dim=x_features, activation=activation)
# )

# nn2.add(
#     tf.keras.layers.Dense(units=65, activation=activation)
# )

# nn2.add(
#     tf.keras.layers.Dense(units=50, activation=activation)
# )

# nn2.add(
#     tf.keras.layers.Dense(units=33, activation=activation)
# )
# # Second hidden layer

# nn2.add(
#     tf.keras.layers.Dense(units=20, activation=activation)
# )


# nn2.add(
#     tf.keras.layers.Dense(units=12, activation=activation)
# )

# nn2.add(
#     tf.keras.layers.Dense(units=6, activation=activation)
# )

# # Output layer
# nn2.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# # Check the structure of the model
# nn2.summary()

In [148]:
#Compile the model
nn2.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [149]:
#Train the model
fit_model = nn2.fit(X_train_scaled,y_train,epochs=50)

Epoch 1/50
804/804 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - accuracy: 0.6893 - loss: 0.6109
Epoch 2/50
804/804 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7280 - loss: 0.5508
Epoch 3/50
804/804 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.7390 - loss: 0.5422
Epoch 4/50
804/804 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.7344 - loss: 0.5463
Epoch 5/50
804/804 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - accuracy: 0.7327 - loss: 0.5433
Epoch 6/50
804/804 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7315 - loss: 0.5438
Epoch 7/50
804/804 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7288 - loss: 0.5470
Epoch 8/50
804/804 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7314 - loss: 0.5444
Epoch 9/50
804/804 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7381 - loss: 0.5390
Epoch 10/50
804/804 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7403 - loss: 0.5337
Epoch 11/50
804/804 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7348 - loss: 0.5380
Epoch 12/50
799/804 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7332 - loss: 0.5409

KeyboardInterrupt:

In [73]:
# def create_model(h):
#     nn = tf.keras.models.Sequential()

#     x_features = len(X_train.iloc[0])
    
#     activation = h.Choice('activation', ['relu','tanh'])
    
#     nn.add(tf.keras.layers.Dense(units=h.Int('first_units',
#         min_value=1,
#         max_value=50,
#         step=2), activation=activation, input_dim=x_features))

#     for i in range(h.Int('num_layers', 1, 15)):
#         nn.add(tf.keras.layers.Dense(units=h.Int('units_' + str(i),
#             min_value=1,
#             max_value=50,
#             step=2),
#             activation=activation))

#     # Output layer
#     nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

#     nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

#     return nn

In [74]:
# tuner = kt.Hyperband(
#     create_model,
#     objective="val_accuracy",
#     max_epochs=30,
#     hyperband_iterations=2)

In [75]:
# tuner.search(X_train_scaled,y_train,epochs=20,validation_data=(X_test_scaled,y_test))

In [76]:
print(tuner.oracle.get_best_trials())

[<keras_tuner.src.engine.trial.Trial object at 0x000001BB3490A930>]

In [77]:
top_hyper = tuner.get_best_hyperparameters(3)
for param in top_hyper:
    print(param.values)

{'activation': 'relu', 'first_units': 41, 'num_layers': 5, 'units_0': 15, 'units_1': 23, 'units_2': 11, 'units_3': 45, 'units_4': 39, 'units_5': 67, 'units_6': 61, 'units_7': 79, 'units_8': 57, 'units_9': 33, 'units_10': 21, 'units_11': 71, 'tuner/epochs': 30, 'tuner/initial_epoch': 10, 'tuner/bracket': 1, 'tuner/round': 1, 'tuner/trial_id': '0076'}
{'activation': 'relu', 'first_units': 49, 'num_layers': 8, 'units_0': 51, 'units_1': 63, 'units_2': 65, 'units_3': 11, 'units_4': 15, 'units_5': 45, 'units_6': 73, 'units_7': 7, 'units_8': 35, 'units_9': 7, 'units_10': 57, 'units_11': 17, 'tuner/epochs': 4, 'tuner/initial_epoch': 0, 'tuner/bracket': 2, 'tuner/round': 0}
{'activation': 'relu', 'first_units': 33, 'num_layers': 11, 'units_0': 23, 'units_1': 23, 'units_2': 23, 'units_3': 31, 'units_4': 13, 'units_5': 55, 'units_6': 55, 'units_7': 1, 'units_8': 35, 'units_9': 61, 'units_10': 57, 'units_11': 51, 'tuner/epochs': 30, 'tuner/initial_epoch': 0, 'tuner/bracket': 0, 'tuner/round': 0}

In [78]:
best_hyper = tuner.get_best_hyperparameters(1)[0]
print(best_hyper.values)

{'activation': 'relu', 'first_units': 41, 'num_layers': 5, 'units_0': 15, 'units_1': 23, 'units_2': 11, 'units_3': 45, 'units_4': 39, 'units_5': 67, 'units_6': 61, 'units_7': 79, 'units_8': 57, 'units_9': 33, 'units_10': 21, 'units_11': 71, 'tuner/epochs': 30, 'tuner/initial_epoch': 10, 'tuner/bracket': 1, 'tuner/round': 1, 'tuner/trial_id': '0076'}

In [ ]:
top_model = tuner.get_best_models(3)
for model in top_model:
    model_loss, model_accuracy = model.evaluate(X_test_scaled,y_test,verbose=2)
    print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 1s - 3ms/step - accuracy: 0.7369 - loss: 0.5479
Loss: 0.547899067401886, Accuracy: 0.7369096279144287
268/268 - 1s - 4ms/step - accuracy: 0.7356 - loss: 0.5523
Loss: 0.552331268787384, Accuracy: 0.7356268167495728
268/268 - 1s - 4ms/step - accuracy: 0.7349 - loss: 0.5558
Loss: 0.5557860136032104, Accuracy: 0.7349271178245544

In [80]:
# Get second best model hyperparameters
second_hyper = tuner.get_best_hyperparameters(2)[1]
second_hyper.values

{'activation': 'relu',
 'first_units': 49,
 'num_layers': 8,
 'units_0': 51,
 'units_1': 63,
 'units_2': 65,
 'units_3': 11,
 'units_4': 15,
 'units_5': 45,
 'units_6': 73,
 'units_7': 7,
 'units_8': 35,
 'units_9': 7,
 'units_10': 57,
 'units_11': 17,
 'tuner/epochs': 4,
 'tuner/initial_epoch': 0,
 'tuner/bracket': 2,
 'tuner/round': 0}

In [81]:
# Compare the performance to the second-best model
second_model = tuner.get_best_models(2)[1]
model_loss, model_accuracy = second_model.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 1s - 4ms/step - accuracy: 0.7356 - loss: 0.5523
Loss: 0.552331268787384, Accuracy: 0.7356268167495728

In [82]:
best_model = tuner.get_best_models(1)[0]
model_loss, model_accuracy = best_model.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 1s - 3ms/step - accuracy: 0.7369 - loss: 0.5479
Loss: 0.547899067401886, Accuracy: 0.7369096279144287

In [ ]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn2.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 1s - 3ms/step - accuracy: 0.7313 - loss: 0.5556
Loss: 0.5555926561355591, Accuracy: 0.7313119769096375

In [84]:
# Export our model to HDF5 file
# create_model().save("nn_HDF5.h5")